// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace Billing.Core.Migrations
{
    [DbContext(typeof(BillingContext))]
    [Migration("20220428152848_SetupInicial")]
    partial class SetupInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CGE.Core.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPFCNPJ")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<decimal?>("CapitalSocial")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("CaracterizacaoCapital")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DtConstituicao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EstadoCivil")
                        .HasColumnType("int");

                    b.Property<string>("Fone1")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Fone2")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Fone3")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("Genero")
                        .HasColumnType("int");

                    b.Property<int>("Nacional")
                        .HasColumnType("int");

                    b.Property<string>("Nacionalidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Porte")
                        .HasColumnType("int");

                    b.Property<string>("Profissao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("QtdQuota")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.Property<int>("TipoEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int");

                    b.Property<decimal?>("VlrQuota")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("WebSite")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPFCNPJ = "01571702000198",
                            CapitalSocial = 20000000m,
                            DtAtualizacao = new DateTime(2022, 4, 28, 12, 28, 48, 5, DateTimeKind.Local).AddTicks(6959),
                            Email = "HALEXFARMACO@HALEX.COM.BR",
                            Fone1 = "5133663806",
                            Nacional = 1,
                            Porte = 5,
                            RazaoSocial = "HALEX ISTAR IND FARMACEUTICA LTDA",
                            Situacao = 0,
                            TipoEmpresa = 1,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 2,
                            CPFCNPJ = "17162579000191",
                            CapitalSocial = 5000000m,
                            DtAtualizacao = new DateTime(2022, 4, 28, 12, 28, 48, 7, DateTimeKind.Local).AddTicks(3314),
                            Email = "CONTATO@LIDERTAXI.COM.BR",
                            Fone1 = "5133663806",
                            Nacional = 1,
                            Porte = 5,
                            RazaoSocial = "LIDER TAXI AEREO S/A AIR BRASIL",
                            Situacao = 0,
                            TipoEmpresa = 1,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 3,
                            CPFCNPJ = "28672087000162",
                            CapitalSocial = 10000100m,
                            DtAtualizacao = new DateTime(2022, 4, 28, 12, 28, 48, 7, DateTimeKind.Local).AddTicks(3333),
                            Email = "CONTATO@SAINTGOBAIN.COM.BR",
                            Fone1 = "5133663806",
                            Nacional = 1,
                            Porte = 5,
                            RazaoSocial = "SAINT GOBAIN CANALIZAÇÃO LTDA",
                            Situacao = 0,
                            TipoEmpresa = 1,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 4,
                            CPFCNPJ = "33113309000147",
                            CapitalSocial = 85000500m,
                            DtAtualizacao = new DateTime(2022, 4, 28, 12, 28, 48, 7, DateTimeKind.Local).AddTicks(3337),
                            Email = "VALIDSOLUCOESSEGURANCA@VALIDSOLUÇÕES.COM.BR",
                            Fone1 = "5133663806",
                            Nacional = 1,
                            Porte = 5,
                            RazaoSocial = "VALID SOLUÇÕES SERVIÇOS DE SEGURANÇA EM MEIOS",
                            Situacao = 0,
                            TipoEmpresa = 1,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 5,
                            CPFCNPJ = "33131079000149",
                            CapitalSocial = 320000100m,
                            DtAtualizacao = new DateTime(2022, 4, 28, 12, 28, 48, 7, DateTimeKind.Local).AddTicks(3339),
                            Email = "CONTATO@CARLZEISS.COM.BR",
                            Fone1 = "5133663806",
                            Nacional = 1,
                            Porte = 5,
                            RazaoSocial = "CARL ZEISS DO BRASIL LTDA",
                            Situacao = 0,
                            TipoEmpresa = 1,
                            TipoPessoa = 1
                        },
                        new
                        {
                            Id = 6,
                            CPFCNPJ = "97672971034",
                            DtAtualizacao = new DateTime(2022, 4, 28, 12, 28, 48, 7, DateTimeKind.Local).AddTicks(3340),
                            DtNascimento = new DateTime(2002, 3, 28, 12, 28, 48, 7, DateTimeKind.Local).AddTicks(3583),
                            Email = "CAMILA_CARGNELUTTI@GMAIL.COM",
                            Fone1 = "5133663806",
                            Genero = 0,
                            Nacional = 1,
                            Porte = 5,
                            Profissao = "NÃO INFORMADO",
                            RazaoSocial = "CAMILA LAIS CARGNELUTTI",
                            Situacao = 0,
                            TipoEmpresa = 1,
                            TipoPessoa = 0
                        },
                        new
                        {
                            Id = 7,
                            CPFCNPJ = "09641388049",
                            DtAtualizacao = new DateTime(2022, 4, 28, 12, 28, 48, 7, DateTimeKind.Local).AddTicks(4452),
                            DtNascimento = new DateTime(1997, 9, 28, 12, 28, 48, 7, DateTimeKind.Local).AddTicks(4457),
                            Email = "RUIPINTO@GMAIL.COM",
                            Fone1 = "5133663806",
                            Genero = 1,
                            Nacional = 1,
                            Porte = 5,
                            Profissao = "NÃO INFORMADO",
                            RazaoSocial = "RUI GARIGHAM PINTO",
                            Situacao = 0,
                            TipoEmpresa = 1,
                            TipoPessoa = 0
                        },
                        new
                        {
                            Id = 8,
                            CPFCNPJ = "94976767787",
                            DtAtualizacao = new DateTime(2022, 4, 28, 12, 28, 48, 7, DateTimeKind.Local).AddTicks(4465),
                            DtNascimento = new DateTime(2007, 1, 28, 12, 28, 48, 7, DateTimeKind.Local).AddTicks(4467),
                            Email = "GILMARVIDAL@GMAIL.COM",
                            Fone1 = "5133663806",
                            Genero = 1,
                            Nacional = 1,
                            Porte = 5,
                            Profissao = "NÃO INFORMADO",
                            RazaoSocial = "GIBRALTAR PEDRO CIPRIANO",
                            Situacao = 0,
                            TipoEmpresa = 1,
                            TipoPessoa = 0
                        },
                        new
                        {
                            Id = 9,
                            CPFCNPJ = "81254784004",
                            DtAtualizacao = new DateTime(2022, 4, 28, 12, 28, 48, 7, DateTimeKind.Local).AddTicks(4470),
                            DtNascimento = new DateTime(2003, 3, 28, 12, 28, 48, 7, DateTimeKind.Local).AddTicks(4471),
                            Email = "ANDREVELHO99@GMAIL.COM",
                            Fone1 = "5133663806",
                            Genero = 1,
                            Nacional = 1,
                            Porte = 5,
                            Profissao = "NÃO INFORMADO",
                            RazaoSocial = "ANDRE BAZACAS VELHO",
                            Situacao = 0,
                            TipoEmpresa = 1,
                            TipoPessoa = 0
                        },
                        new
                        {
                            Id = 10,
                            CPFCNPJ = "46056564053",
                            DtAtualizacao = new DateTime(2022, 4, 28, 12, 28, 48, 7, DateTimeKind.Local).AddTicks(4473),
                            DtNascimento = new DateTime(1999, 12, 28, 12, 28, 48, 7, DateTimeKind.Local).AddTicks(4475),
                            Email = "GILMARTH90@GMAIL.COM",
                            Fone1 = "5133663806",
                            Genero = 1,
                            Nacional = 1,
                            Porte = 5,
                            Profissao = "NÃO INFORMADO",
                            RazaoSocial = "GILMAR THUME",
                            Situacao = 0,
                            TipoEmpresa = 1,
                            TipoPessoa = 0
                        },
                        new
                        {
                            Id = 11,
                            CPFCNPJ = "28866991015",
                            DtAtualizacao = new DateTime(2022, 4, 28, 12, 28, 48, 7, DateTimeKind.Local).AddTicks(4477),
                            DtNascimento = new DateTime(2000, 7, 28, 12, 28, 48, 7, DateTimeKind.Local).AddTicks(4479),
                            Email = "CLEICEZAGO@GMAIL.COM",
                            Fone1 = "5133663806",
                            Genero = 0,
                            Nacional = 1,
                            Porte = 5,
                            Profissao = "NÃO INFORMADO",
                            RazaoSocial = "CLEICE AMABILE LEVY ZAGO",
                            Situacao = 0,
                            TipoEmpresa = 1,
                            TipoPessoa = 0
                        },
                        new
                        {
                            Id = 12,
                            CPFCNPJ = "93233728034",
                            DtAtualizacao = new DateTime(2022, 4, 28, 12, 28, 48, 7, DateTimeKind.Local).AddTicks(4481),
                            DtNascimento = new DateTime(1998, 3, 28, 12, 28, 48, 7, DateTimeKind.Local).AddTicks(4483),
                            Email = "MONICACRIS88@GMAIL.COM",
                            Fone1 = "5133663806",
                            Genero = 0,
                            Nacional = 1,
                            Porte = 5,
                            Profissao = "NÃO INFORMADO",
                            RazaoSocial = "MONICA CRISTIANE RINCK",
                            Situacao = 0,
                            TipoEmpresa = 1,
                            TipoPessoa = 0
                        },
                        new
                        {
                            Id = 13,
                            CPFCNPJ = "78508614004",
                            DtAtualizacao = new DateTime(2022, 4, 28, 12, 28, 48, 7, DateTimeKind.Local).AddTicks(4485),
                            DtNascimento = new DateTime(2004, 2, 28, 12, 28, 48, 7, DateTimeKind.Local).AddTicks(4486),
                            Email = "ALVAROM@GMAIL.COM",
                            Fone1 = "5133663806",
                            Genero = 1,
                            Nacional = 1,
                            Porte = 5,
                            Profissao = "NÃO INFORMADO",
                            RazaoSocial = "ALVARO MARQUES TEIXEIRA",
                            Situacao = 0,
                            TipoEmpresa = 1,
                            TipoPessoa = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
